api_version = "2025-10"

[[extensions]]
name = "upsell-on-checkout"
handle = "upsell-on-checkout"
uid = "c3ea9523-2fb6-6643-df2a-18c9ba869144e52575ba"
type = "ui_extension"

[[extensions.targeting]]
module = "./src/Checkout.jsx"
target = "purchase.checkout.block.render"

[extensions.capabilities]
network_access = true